### ISSUE TITLE
Use measurement from SpaceAPI?

### ISSUE THREAD

**Issue by stefan2904** [realraum/r3pi-temperature#1]
The [realraum SpaceAPI](http://realraum.at/status.json) provides a temperature measurement in _sensors -> temperature -> 0 -> value_. Use this value instead of the own measurement and use the temperature sensor somewhere else?

**Comment by PeterTheOne** [comment]
suggestions: basement temperature? laser temperature?

**Comment by btittelbach** [comment]
basement temperature and humidity would be great. I bought a DHT11 sensor for that, ages ago, but have not yet gotten around to putting it on a raspberry. There is probably ready-to-use code for that around, so would be great it we could have some basement data :)

**Comment by btittelbach** [comment]
would be even better, if we could add the data to the spaceapi... should be just a small python script akin to https://github.com/realraum/door_and_sensors/blob/master/scripts/bridge-old-sensors-zmq.py on your end

**Comment by stefan2904** [comment]
uses measurement from spaceAPI since 89adb1fcff186ab18fbe3a78e3b1d73f1e82d643, because we don't have any sensors left and I need at least one for camp.
so please dont breake the spaceAPI temperature sensor now. ;-)

**Comment by stefan2904** [comment]
@PeterTheOne @btittelbach could you create a separate issue for that?
